upstream fastcgi_backend {
    server php:9000;
}


server {

    listen 80;

    server_name localhost;

    root /var/www/html/pub;

    index index.php;

    charset utf-8;


    # ========================================================
    # MAIN LOCATION
    # ========================================================

    location / {

        try_files $uri $uri/ /index.php?$args;

    }


    # ========================================================
    # PHP
    # ========================================================

    location ~ ^/(index|get|static|errors/report|errors/404|errors/503)\.php$ {

        try_files $uri =404;

        fastcgi_pass fastcgi_backend;

        fastcgi_buffers 16 16k;

        fastcgi_buffer_size 32k;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        include fastcgi_params;

        fastcgi_read_timeout 600;

    }


    # ========================================================
    # STATIC CONTENT
    # ========================================================

    location /static/ {

        location ~ ^/static/version {

            rewrite ^/static/(version\d*/)?(.*)$ /static/$2 last;

        }

        try_files $uri $uri/ /static.php?resource=$uri&$args;

    }


    # ========================================================
    # MEDIA
    # ========================================================

    location /media/ {

        try_files $uri $uri/ /get.php?$args;

    }


    # ========================================================
    # SECURITY
    # ========================================================

    location ~ /\. {

        deny all;

    }

    location ~* /(app|var|vendor|generated|lib|setup|update)/ {

        deny all;

    }

}
